/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Chave10RouteImport } from './routes/chave10'
import { Route as VendaFacilRouteImport } from './routes/venda-facil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Chave10Route = Chave10RouteImport.update({
  id: '/chave10',
  path: '/chave10',
  getParentRoute: () => rootRouteImport,
} as any)
const VendaFacilRoute = VendaFacilRouteImport.update({
  id: '/venda-facil',
  path: '/venda-facil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chave10': typeof Chave10Route
  '/venda-facil': typeof VendaFacilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chave10': typeof Chave10Route
  '/venda-facil': typeof VendaFacilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chave10': typeof Chave10Route
  '/venda-facil': typeof VendaFacilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chave10' | '/venda-facil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chave10' | '/venda-facil'
  id: '__root__' | '/' | '/chave10' | '/venda-facil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Chave10Route: typeof Chave10Route
  VendaFacilRoute: typeof VendaFacilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chave10': {
      id: '/chave10'
      path: '/chave10'
      fullPath: '/chave10'
      preLoaderRoute: typeof Chave10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venda-facil': {
      id: '/venda-facil'
      path: '/venda-facil'
      fullPath: '/venda-facil'
      preLoaderRoute: typeof VendaFacilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Chave10Route: Chave10Route,
  VendaFacilRoute: VendaFacilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
